// <auto-generated />
namespace TaskAssessor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JobModel_removedAddedBy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobModel_removedAddedBy));
        
        string IMigrationMetadata.Id
        {
            get { return "201712071539081_JobModel_removedAddedBy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
