// <auto-generated />
namespace TaskAssessor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedValidation_HourInterval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedValidation_HourInterval));
        
        string IMigrationMetadata.Id
        {
            get { return "201801091138046_AddedValidation_HourInterval"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
